{% set version = "0.7.4" %}

package:
  name: torch_em
  version: {{ version }}

source:
  url: https://github.com/constantinpape/torch_em/archive/{{ version }}.tar.gz
  sha256: 2ec7160940cdc68b6674399eb822ac5e77536920feb0d8b6b3762d4d83a11705

build:
  number: 0
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - bioimageio.core >=0.6.1
    - bioimageio.spec >=0.5.2
    - kornia
    - python >=3.6
    - python-elf >=0.4.8
    - pytorch
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - timm

test:
  imports:
    - torch_em
  source_files:
    - test/**/*.py
  commands:
    - python -m unittest discover -s test -v

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Deep-learning based semantic and instance segmentation for 3D Electron Microscopy and other bioimage analysis problems based on pytorch.
  home: https://github.com/constantinpape/torch-em

extra:
  recipe-maintainers:
    - constantinpape
