{% set version = "0.7.9" %}
{% set python_min = "3.10" %}

package:
  name: torch_em
  version: {{ version }}

source:
  url: https://github.com/constantinpape/torch_em/archive/{{ version }}.tar.gz
  sha256: 8222669fd429f1b08df282c1610196db1a04c285f79cd5cb268e003452075206
  patches:
    - fix_compile_test.patch

build:
  number: 0
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - bioimageio.core >=0.8.0
    - bioimageio.spec >=0.5.2
    - kornia
    - natsort
    - nifty >=1.2.3
    - python >={{ python_min }}
    - python-elf >=0.4.8
    - pytorch
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - timm

test:
  requires:
    - python {{ python_min }}
  imports:
    - torch_em
  source_files:
    - test/**/*.py
  commands:
    - python -m unittest discover -s test -v

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Deep-learning based semantic and instance segmentation for 3D Electron Microscopy and other bioimage analysis problems based on pytorch.
  home: https://github.com/constantinpape/torch-em

extra:
  recipe-maintainers:
    - constantinpape
